### ISSUE TITLE
Manual scrobbles not transfered to wilt when there's a "scrobbling now" on lastfm

### ISSUE THREAD

**Issue by lapagen** [ModalSeoul/Ripfm#1]
Test 1: There's a "scrobbling now" song on my lastfm profile but I paused/stopped it. Manually scrobbling another song's worked fine, but it's not transfered to wilt.

Test 2: Trying again. Same result

Test 3: Trying again, but the "scrobbling now" status is gone _(and the "scrobbling now" song hasn't been scrobbled as I'd not left it playing for long enough)_. The manual scrobble got transfered. The two previous ones weren't then and aren't now neither.

**Comment by ModalSeoul** [comment]
This isn't an issue nor will it be addressed as one. RipFM works by grabbing what you're listening to from Last, and scrobbling it to Wilt. That is what it does.
